### ISSUE TITLE
come back please i'm sorry

### ISSUE THREAD

**Issue by discoli** [sillibird/nimhq#1]
come back please i'm sorry

**Comment by discoli** [comment]
######## :(

**Comment by discoli** [comment]
issue solved, thank you

**Comment by discoli** [comment]
sillibird please actually come back

**Comment by ReXiaPrevail** [comment]
Silli, we're actually sorry :(

(please come back)

**Comment by KidJunky** [comment]
not gonna lie, we need your presence back

come back please

**Comment by VividVivix** [comment]
silly bird come back

**Comment by ReXiaPrevail** [comment]
silli pls

**Comment by lorpus** [comment]
nigga toilet

**Comment by discoli** [comment]
sillibruh come back

**Comment by discoli** [comment]
ok issue solved thanks for everyone who was involved

**Comment by discoli** [comment]
discoli apologises formally

**Comment by lorpus** [comment]
nigga toilet

**Comment by SolitudeSF** [comment]
bro, please

**Comment by leventea** [comment]
please come back man
